# Pills

add_newline = false
palette = "default"

right_format = """
$cmd_duration\
"""

format = """
[â•­](fg:separator)\
$status\
$directory\
$git_branch\
$git_status\
$time\
$line_break\
[â•°](fg:separator)\
$character\
"""

###########################################

[palettes.default]
prompt_ok  = "#8047c1"
prompt_err = "#e23140"
icon       = "#161514"
separator  = "#35312c"
background = "#35312c"

directory  = "#9f31e2"
duration   = "#e26f31"
status     = "#e23140"
git_branch = "#31e268"
git_status = "#31e268"

###########################################

[character]
success_symbol = "[â¯](fg:prompt_ok)"
error_symbol = "[â¯](fg:prompt_err)"

[status]
format = "[â”€](fg:separator)[î‚¶](fg:status)[î½¶](fg:icon bg:status)[î‚´](fg:status bg:background)[ $status](bg:background)[î‚´](fg:background)"
pipestatus = true
pipestatus_separator = "-"
pipestatus_segment_format = "$status"
pipestatus_format = "[â”€](fg:separator)[î‚¶](fg:status)[î½¶](fg:icon bg:status)[î‚´](fg:status bg:background)[ $pipestatus](bg:background)[î‚´](fg:background)"
disabled = false

[directory]
format = "[â”€](fg:separator)[î‚¶](fg:directory)[ï»](fg:icon bg:directory)[î‚´](fg:directory bg:background)[ $path](bg:background)[î‚´](fg:background)"
truncate_to_repo = false
truncation_length = 0

[directory.substitutions]
"Documents" = "ó°ˆ™"
"Downloads" = "ï€™"
"Music" = "ó°š"
"Pictures" = "ï€¾"
"Repos" = "ó°²‹"
"Programing" = "ğŸ˜ˆ"
"~" = "ó° ¦"
".config" = 'î—¼'

[git_branch]
format = "[â”€](fg:separator)[î‚¶](fg:git_branch)[î‚ ](fg:icon bg:git_branch)[î‚´](fg:git_branch bg:background)[ $branch](bg:background)"

[git_status]
conflicted ='âš”ï¸'
ahead = 'ğŸªğŸ’¨'
behind = 'ğŸ˜°'
diverged= 'ğŸ˜µ'
up_to_date = 'âœ”'
untracked = 'ğŸ¤·'
stashed = 'ğŸ“¦'
modified = 'ğŸ“'
staged = '[++\($count\)](fg:#98c379.bg:#394260)($style)'
renamed = 'ğŸ‘…'
deleted = 'ğŸ—‘'
format = "[î‚´](fg:background bg:git_status)[$all_status$ahead_behind](fg:icon bg:git_status)[î‚´](fg:git_status)"

[cmd_duration]
format = "[â”€](fg:separator)[î‚¶](fg:duration)[ó±‹](fg:icon bg:duration)[î‚´](fg:duration bg:background)[ $duration](bg:background)[î‚´](fg:background)"
min_time = 1000

[time]
format = "[â”€](fg:separator)[î‚¶](fg:duration)[ó°¥”](fg:icon bg:duration)[î‚´](fg:duration bg:background)[ $time](bg:background)[î‚´](fg:background)"
disabled = true
